sync-iam-rucio-dev:
    description: "Sync Indigo IAM users with a Rucio server"
    module_name: "tasks.sync.iam"
    class_name: "SyncIndigoIAMRucio"
    enabled: true
    args:
    kwargs:
      oidc_issuer_url: https://ska-iam.stfc.ac.uk/
      client_id: 05194e43-b356-447f-825f-6377cdaa48a5
      client_secret:
      rucio_user_iam_groups:
        - services/rucio/roles/user
      rucio_admin_iam_groups:
        - services/rucio/roles/admin
      service_accounts:
        service_chsrc_ingestion:
          id: 59289c21-4bde-427a-99aa-b73d8dafd1ce
          email: "someone@somewhere.com"
        service_skaosrc_rtm:
          id: c783963c-9472-4aa2-8b93-1b09447a58e9
          email: "someone@somewhere.com"
      skip_accounts:
        - root
      rse_quota: 1000000000000
      dry_run: False
      output:
        databases:
          #- type: es
          #  uri: https://monit.srcdev.skao.int/elastic
          #  index: rucio-task-manager.skao-dev.tasks.sync.iam-to-rucio
