image:
  repository: registry.gitlab.com/ska-telescope/src/ska-rucio-task-manager
  tag: release-1.29.0
  pullPolicy: Always

deployment:
  namespace: rucio-task-manager

config:
  RUCIO_CFG_RUCIO_HOST: https://srcdev.skatelescope.org/rucio-dev
  RUCIO_CFG_AUTH_HOST: https://srcdev.skatelescope.org/rucio-dev
  RUCIO_CFG_ACCOUNT: robbarnsley
  RUCIO_CFG_AUTH_TYPE: oidc
  RUCIO_CFG_USERNAME:
  RUCIO_CFG_PASSWORD:
  VOMS: skatelescope.eu

secrets:
  - name: OIDC_AGENT_AUTH_CLIENT_CFG_VALUE
    fromSecretName: oidc-agent-auth-client
    fromSecretKey: cfg
  - name: OIDC_AGENT_AUTH_CLIENT_CFG_PASSWORD
    fromSecretName: oidc-agent-auth-client
    fromSecretKey: password
  - name: KUBE_CONFIG_VALUE
    fromSecretName: kube
    fromSecretKey: cfg.dev
  - name: RUCIO_CFG_CLIENT_CERT_VALUE
    fromSecretName: rucio-cfg-client
    fromSecretKey: certificate
  - name: RUCIO_CFG_CLIENT_KEY_VALUE
    fromSecretName: rucio-cfg-client
    fromSecretKey: key
  - name: TASK_SYNC_IAM_RUCIO_CLIENT_SECRET
    fromSecretName: task-sync-iam-rucio
    fromSecretKey: client_secret

cronjobs:
  - name: stubs
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    task_file_path: "etc/tasks/stubs.yml"
    disabled: yes
    volumes:
      - name: some-name
        persistentVolumeClaim:
          claimName: claim-name
    volumeMounts:
      - name: some-name
        mountPath: "/path/"
