get-daemon-info-dev:
  description: "Get daemon information from k8s cluster"
  module_name: "tasks.probes.daemons"
  class_name: "ProbesDaemons"
  enabled: true
  args:
  kwargs:
    cluster_host: 192.168.50.228
    cluster_port: 6443
    cluster_service_account_token:
    # see https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#without-kubectl-proxy
    # and https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/
    daemon_like_names:
      - abacus-account
      - abacus-rse
      - conveyor-finisher
      - conveyor-poller
      - conveyor-submitter
      - hermes2
      - judge-cleaner
      - judge-evaluator
      - judge-injector
      - judge-repairer
      - reaper
      - transmogrifier
      - undertaker
    namespace: rucio-test
    output:
      databases:
        - type: es
          uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
          index: rucio-task-manager.skao-dev.tasks.probes.daemons
