get-service-heartbeats-dev:
  description: "Get service heartbeats"
  module_name: "tasks.probes.service_heartbeats"
  class_name: "ProbesServiceHeartbeats"
  enabled: true
  args:
  kwargs:
    services:
      - name: rucio
        endpoint: https://srcdev.skatelescope.org/rucio-dev/ping
        expected_status_code: 200
        expected_content:
          version: 1.29.0
      - name: fts
        endpoint: https://fts3-pilot.cern.ch:8449
        expected_status_code: 200
        expected_content:
    output:
      databases:
        - type: es
          uri: https://srcdev.skatelescope.org/rucio-dev/monit/elastic/
          index: rucio-task-manager.skao-dev.tasks.probes.service_heartbeats
